/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisped.visao;

import javax.swing.JOptionPane;

/**
 *
 * @author JVM
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneTelaPrincipal = new javax.swing.JDesktopPane();
        lblUsuarioTelaPrincipal = new javax.swing.JLabel();
        lblDataTelaPrincipal = new javax.swing.JLabel();
        jMenuTelaPrincipal = new javax.swing.JMenuBar();
        jMenuCadTelaPrincipal = new javax.swing.JMenu();
        jMenuCadUsuTelaPrincipal = new javax.swing.JMenuItem();
        jMenuCadRHTelaPrincipal = new javax.swing.JMenuItem();
        jMenuCadInfPTelaPrincipal = new javax.swing.JMenuItem();
        jMenuCadServTelaPrincipal = new javax.swing.JMenuItem();
        jMenuCadMatTelaPrincipal = new javax.swing.JMenuItem();
        jMenuCadContTelaPrincipal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISP&D - SISTEMA PARA CONTROLE DE PROJETOS DE INOVAÇÃO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPaneTelaPrincipal.setPreferredSize(new java.awt.Dimension(640, 460));

        javax.swing.GroupLayout jDesktopPaneTelaPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneTelaPrincipal);
        jDesktopPaneTelaPrincipal.setLayout(jDesktopPaneTelaPrincipalLayout);
        jDesktopPaneTelaPrincipalLayout.setHorizontalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jDesktopPaneTelaPrincipalLayout.setVerticalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUsuarioTelaPrincipal.setText("Usuário");

        lblDataTelaPrincipal.setText("Data");

        jMenuCadTelaPrincipal.setText("Cadastrar");
        jMenuCadTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadTelaPrincipalActionPerformed(evt);
            }
        });

        jMenuCadUsuTelaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadUsuTelaPrincipal.setText("Usuário");
        jMenuCadUsuTelaPrincipal.setEnabled(false);
        jMenuCadUsuTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadUsuTelaPrincipalActionPerformed(evt);
            }
        });
        jMenuCadTelaPrincipal.add(jMenuCadUsuTelaPrincipal);

        jMenuCadRHTelaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadRHTelaPrincipal.setText("Informações de RH");
        jMenuCadRHTelaPrincipal.setEnabled(false);
        jMenuCadRHTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadRHTelaPrincipalActionPerformed(evt);
            }
        });
        jMenuCadTelaPrincipal.add(jMenuCadRHTelaPrincipal);

        jMenuCadInfPTelaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadInfPTelaPrincipal.setText("Informções do Projeto");
        jMenuCadInfPTelaPrincipal.setEnabled(false);
        jMenuCadTelaPrincipal.add(jMenuCadInfPTelaPrincipal);

        jMenuCadServTelaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadServTelaPrincipal.setText("Serviços de Terceiros");
        jMenuCadServTelaPrincipal.setEnabled(false);
        jMenuCadTelaPrincipal.add(jMenuCadServTelaPrincipal);

        jMenuCadMatTelaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadMatTelaPrincipal.setText("Materiais de consumo");
        jMenuCadMatTelaPrincipal.setEnabled(false);
        jMenuCadMatTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadMatTelaPrincipalActionPerformed(evt);
            }
        });
        jMenuCadTelaPrincipal.add(jMenuCadMatTelaPrincipal);

        jMenuCadContTelaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadContTelaPrincipal.setText("Informações Contábeis");
        jMenuCadContTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadContTelaPrincipalActionPerformed(evt);
            }
        });
        jMenuCadTelaPrincipal.add(jMenuCadContTelaPrincipal);

        jMenuTelaPrincipal.add(jMenuCadTelaPrincipal);

        jMenu2.setText("Relatório");
        jMenuTelaPrincipal.add(jMenu2);

        jMenu3.setText("Opções");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Sair");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Trocar de Usuário");
        jMenu3.add(jMenuItem1);

        jMenuTelaPrincipal.add(jMenu3);

        setJMenuBar(jMenuTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarioTelaPrincipal)
                    .addComponent(lblDataTelaPrincipal))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuarioTelaPrincipal)
                        .addGap(59, 59, 59)
                        .addComponent(lblDataTelaPrincipal)
                        .addGap(0, 366, Short.MAX_VALUE))
                    .addComponent(jDesktopPaneTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(915, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadUsuTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadUsuTelaPrincipalActionPerformed
        TelaCadastroUsuario telaCadastroUsuario = new  TelaCadastroUsuario();
        telaCadastroUsuario.setVisible(true);
        jDesktopPaneTelaPrincipal.add(telaCadastroUsuario);
    }//GEN-LAST:event_jMenuCadUsuTelaPrincipalActionPerformed

    private void jMenuCadMatTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadMatTelaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadMatTelaPrincipalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int sair  = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair", "Atenção",JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuCadTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadTelaPrincipalActionPerformed
   
    }//GEN-LAST:event_jMenuCadTelaPrincipalActionPerformed

    private void jMenuCadRHTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadRHTelaPrincipalActionPerformed
       TelaCadastroRH telaCadastroRH = new TelaCadastroRH ();
       telaCadastroRH.setVisible(true);
       jDesktopPaneTelaPrincipal.add(telaCadastroRH);
    }//GEN-LAST:event_jMenuCadRHTelaPrincipalActionPerformed

    private void jMenuCadContTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadContTelaPrincipalActionPerformed
      TelaCadastroContabil telaCadastroContabil =  new TelaCadastroContabil ();
      telaCadastroContabil.setVisible(true);
      jDesktopPaneTelaPrincipal.add(telaCadastroContabil);
    }//GEN-LAST:event_jMenuCadContTelaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneTelaPrincipal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    public static javax.swing.JMenuItem jMenuCadContTelaPrincipal;
    private javax.swing.JMenuItem jMenuCadInfPTelaPrincipal;
    private javax.swing.JMenuItem jMenuCadMatTelaPrincipal;
    public static javax.swing.JMenuItem jMenuCadRHTelaPrincipal;
    private javax.swing.JMenuItem jMenuCadServTelaPrincipal;
    public static javax.swing.JMenu jMenuCadTelaPrincipal;
    public static javax.swing.JMenuItem jMenuCadUsuTelaPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuBar jMenuTelaPrincipal;
    private javax.swing.JLabel lblDataTelaPrincipal;
    private javax.swing.JLabel lblUsuarioTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
